// Country/flag quiz data for the Flags Quiz app
export const countries = [
  { key: 'albania', name: 'Albania', capital: 'Tirana', continent: 'Europe', government: 'Republic', language: 'Albanian', isoCode: 'al' },
  { key: 'austria', name: 'Austria', capital: 'Vienna', continent: 'Europe', government: 'Republic', language: 'German', isoCode: 'at' },
  { key: 'belgium', name: 'Belgium', capital: 'Brussels', continent: 'Europe', government: 'Monarchy', language: 'French, German, Dutch', isoCode: 'be' },
  { key: 'britain', name: 'Great Britain', capital: 'London', continent: 'Europe', government: 'Constitutional monarchy', language: 'English', isoCode: 'gb' },
  { key: 'croatia', name: 'Croatia', capital: 'Zagreb', continent: 'Europe', government: 'Republic', language: 'Croatian', isoCode: 'hr' },
  { key: 'czech', name: 'Czech Republic', capital: 'Prague', continent: 'Europe', government: 'Republic', language: 'Czech', isoCode: 'cz' },
  { key: 'estonia', name: 'Estonia', capital: 'Tallinn', continent: 'Europe', government: 'Republic', language: 'Estonian', isoCode: 'ee' },
  { key: 'finland', name: 'Finland', capital: 'Helsinki', continent: 'Europe', government: 'Republic', language: 'Finnish, Swedish', isoCode: 'fi' },
  { key: 'france', name: 'France', capital: 'Paris', continent: 'Europe', government: 'Republic', language: 'French', isoCode: 'fr' },
  { key: 'germany', name: 'Germany', capital: 'Berlin', continent: 'Europe', government: 'Republic', language: 'German', isoCode: 'de' },
  { key: 'greece', name: 'Greece', capital: 'Athens', continent: 'Europe', government: 'Republic', language: 'Greek', isoCode: 'gr' },
  { key: 'hungary', name: 'Hungary', capital: 'Budapest', continent: 'Europe', government: 'Republic', language: 'Hungarian', isoCode: 'hu' },
  { key: 'iceland', name: 'Iceland', capital: 'Reykjavik', continent: 'Europe', government: 'Republic', language: 'Icelandic', isoCode: 'is' },
  { key: 'italy', name: 'Italy', capital: 'Rome', continent: 'Europe', government: 'Republic', language: 'Italian', isoCode: 'it' },
  { key: 'latvia', name: 'Latvia', capital: 'Riga', continent: 'Europe', government: 'Republic', language: 'Latvian', isoCode: 'lv' },
  { key: 'luxembourg', name: 'Luxembourg', capital: 'Luxembourg', continent: 'Europe', government: 'Constitutional monarchy', language: 'French, Luxembourgish, German', isoCode: 'lu' },
  { key: 'macedonia', name: 'North Macedonia', capital: 'Skopje', continent: 'Europe', government: 'Republic', language: 'Macedonian', isoCode: 'mk' },
  { key: 'netherlands', name: 'Netherlands', capital: 'Amsterdam', continent: 'Europe', government: 'Constitutional monarchy', language: 'Dutch', isoCode: 'nl' },
  { key: 'norway', name: 'Norway', capital: 'Oslo', continent: 'Europe', government: 'Constitutional monarchy', language: 'Norwegian', isoCode: 'no' },
  { key: 'poland', name: 'Poland', capital: 'Warsaw', continent: 'Europe', government: 'Republic', language: 'Polish', isoCode: 'pl' },
  { key: 'portugal', name: 'Portugal', capital: 'Lisbon', continent: 'Europe', government: 'Republic', language: 'Portuguese', isoCode: 'pt' },
  { key: 'russia', name: 'Russian Federation', capital: 'Moscow', continent: 'Europe', government: 'Republic', language: 'Russian', isoCode: 'ru' },
  { key: 'slovakia', name: 'Slovakia', capital: 'Bratislava', continent: 'Europe', government: 'Republic', language: 'Slovak', isoCode: 'sk' },
  { key: 'spain', name: 'Spain', capital: 'Madrid', continent: 'Europe', government: 'Constitutional monarchy', language: 'Spanish', isoCode: 'es' },
  { key: 'sweden', name: 'Sweden', capital: 'Stockholm', continent: 'Europe', government: 'Constitutional monarchy', language: 'Swedish', isoCode: 'se' },
  { key: 'switzerland', name: 'Switzerland', capital: 'Bern', continent: 'Europe', government: 'Republic', language: 'German, French, Romansh, Italian', isoCode: 'ch' },
  { key: 'ukraine', name: 'Ukraine', capital: 'Kyiv', continent: 'Europe', government: 'Republic', language: 'Ukrainian', isoCode: 'ua' },
  { key: 'afghanistan', name: 'Afghanistan', capital: 'Kabul', continent: 'Asia', government: 'Islamic republic', language: 'Pashto, Dari', isoCode: 'af' },
  { key: 'australia', name: 'Australia', capital: 'Canberra', continent: 'Oceania', government: 'Constitutional monarchy', language: 'English', isoCode: 'au' },
  { key: 'china', name: 'China', capital: 'Beijing', continent: 'Asia', government: 'Communist state', language: 'Chinese', isoCode: 'cn' },
  { key: 'india', name: 'India', capital: 'New Delhi', continent: 'Asia', government: 'Republic', language: 'Hindi, English', isoCode: 'in' },
  { key: 'iraq', name: 'Iraq', capital: 'Baghdad', continent: 'Asia', government: 'Republic', language: 'Arabic, Kurdish', isoCode: 'iq' },
  { key: 'israel', name: 'Israel', capital: 'Jerusalem', continent: 'Asia', government: 'Republic', language: 'Hebrew, Arabic', isoCode: 'il' },
  { key: 'japan', name: 'Japan', capital: 'Tokyo', continent: 'Asia', government: 'Constitutional monarchy', language: 'Japanese', isoCode: 'jp' },
  { key: 'jordan', name: 'Jordan', capital: 'Amman', continent: 'Asia', government: 'Constitutional monarchy', language: 'Arabic', isoCode: 'jo' },
  { key: 'kazakhstan', name: 'Kazakhstan', capital: 'Nur-Sultan', continent: 'Asia', government: 'Presidential republic', language: 'Kazakh, Russian', isoCode: 'kz' },
  { key: 'korea', name: 'South Korea', capital: 'Seoul', continent: 'Asia', government: 'Republic', language: 'Korean', isoCode: 'kr' },
  { key: 'kuwait', name: 'Kuwait', capital: 'Kuwait City', continent: 'Asia', government: 'Constitutional monarchy', language: 'Arabic', isoCode: 'kw' },
  { key: 'kyrgyzstan', name: 'Kyrgyzstan', capital: 'Bishkek', continent: 'Asia', government: 'Republic', language: 'Kyrgyz, Russian', isoCode: 'kg' },
  { key: 'malaysia', name: 'Malaysia', capital: 'Kuala Lumpur', continent: 'Asia', government: 'Constitutional monarchy', language: 'Malay', isoCode: 'my' },
  { key: 'mongolia', name: 'Mongolia', capital: 'Ulaanbaatar', continent: 'Asia', government: 'Republic', language: 'Mongolian', isoCode: 'mn' },
  { key: 'nepal', name: 'Nepal', capital: 'Kathmandu', continent: 'Asia', government: 'Republic', language: 'Nepali', isoCode: 'np' },
  { key: 'philippines', name: 'Philippines', capital: 'Manila', continent: 'Asia', government: 'Republic', language: 'English, Filipino', isoCode: 'ph' },
  { key: 'qatar', name: 'Qatar', capital: 'Doha', continent: 'Asia', government: 'Absolute monarchy', language: 'Arabic', isoCode: 'qa' },
  { key: 'saudi', name: 'Saudi Arabia', capital: 'Riyadh', continent: 'Asia', government: 'Absolute monarchy', language: 'Arabic', isoCode: 'sa' },
  { key: 'singapore', name: 'Singapore', capital: 'Singapore', continent: 'Asia', government: 'Republic', language: 'English, Malay, Tamil, Mandarin', isoCode: 'sg' },
  { key: 'taiwan', name: 'Taiwan', capital: 'Taipei', continent: 'Asia', government: 'Republic', language: 'Mandarin', isoCode: 'tw' },
  { key: 'uzbekistan', name: 'Uzbekistan', capital: 'Tashkent', continent: 'Asia', government: 'Republic', language: 'Uzbek', isoCode: 'uz' },
  { key: 'vietnam', name: 'Vietnam', capital: 'Hanoi', continent: 'Asia', government: 'Communist state', language: 'Vietnamese', isoCode: 'vn' },
  { key: 'argentina', name: 'Argentina', capital: 'Buenos Aires', continent: 'South America', government: 'Republic', language: 'Spanish', isoCode: 'ar' },
  { key: 'bahamas', name: 'Bahamas', capital: 'Nassau', continent: 'North America', government: 'Constitutional monarchy', language: 'English', isoCode: 'bs' },
  { key: 'bolivia', name: 'Bolivia', capital: 'La Paz', continent: 'South America', government: 'Republic', language: 'Spanish', isoCode: 'bo' },
  { key: 'brazil', name: 'Brazil', capital: 'Brasília', continent: 'South America', government: 'Republic', language: 'Portuguese', isoCode: 'br' },
  { key: 'canada', name: 'Canada', capital: 'Ottawa', continent: 'North America', government: 'Constitutional monarchy', language: 'English, French', isoCode: 'ca' },
  { key: 'chile', name: 'Chile', capital: 'Santiago', continent: 'South America', government: 'Republic', language: 'Spanish', isoCode: 'cl' },
  { key: 'cuba', name: 'Cuba', capital: 'Havana', continent: 'North America', government: 'Socialist republic', language: 'Spanish', isoCode: 'cu' },
  { key: 'domrep', name: 'Dominican Republic', capital: 'Santo Domingo', continent: 'North America', government: 'Republic', language: 'Spanish', isoCode: 'do' },
  { key: 'ecuador', name: 'Ecuador', capital: 'Quito', continent: 'South America', government: 'Republic', language: 'Spanish', isoCode: 'ec' },
  { key: 'haiti', name: 'Haiti', capital: 'Port-au-Prince', continent: 'North America', government: 'Republic', language: 'French, Haitian Creole', isoCode: 'ht' },
  { key: 'jamaica', name: 'Jamaica', capital: 'Kingston', continent: 'North America', government: 'Constitutional monarchy', language: 'English', isoCode: 'jm' },
  { key: 'mexico', name: 'Mexico', capital: 'Mexico City', continent: 'North America', government: 'Republic', language: 'Spanish', isoCode: 'mx' },
  { key: 'peru', name: 'Peru', capital: 'Lima', continent: 'South America', government: 'Republic', language: 'Spanish', isoCode: 'pe' },
  { key: 'uruguay', name: 'Uruguay', capital: 'Montevideo', continent: 'South America', government: 'Republic', language: 'Spanish', isoCode: 'uy' },
  { key: 'usa', name: 'United States of America', capital: 'Washington, D.C.', continent: 'North America', government: 'Republic', language: 'English', isoCode: 'us' },
  { key: 'venezuela', name: 'Venezuela', capital: 'Caracas', continent: 'South America', government: 'Republic', language: 'Spanish', isoCode: 've' },
  { key: 'algeria', name: 'Algeria', capital: 'Algiers', continent: 'Africa', government: 'Presidential republic', language: 'Arabic', isoCode: 'dz' },
  { key: 'angola', name: 'Angola', capital: 'Luanda', continent: 'Africa', government: 'Republic', language: 'Portuguese', isoCode: 'ao' },
  { key: 'cameron', name: 'Cameroon', capital: 'Yaoundé', continent: 'Africa', government: 'Republic', language: 'French, English', isoCode: 'cm' },
  { key: 'chad', name: 'Chad', capital: "N'Djamena", continent: 'Africa', government: 'Presidential republic', language: 'French, Arabic', isoCode: 'td' },
  { key: 'egypt', name: 'Egypt', capital: 'Cairo', continent: 'Africa', government: 'Republic', language: 'Arabic', isoCode: 'eg' },
  { key: 'ethiopia', name: 'Ethiopia', capital: 'Addis Ababa', continent: 'Africa', government: 'Republic', language: 'Amharic', isoCode: 'et' },
  { key: 'gambia', name: 'Gambia', capital: 'Banjul', continent: 'Africa', government: 'Republic', language: 'English', isoCode: 'gm' },
  { key: 'ghana', name: 'Ghana', capital: 'Accra', continent: 'Africa', government: 'Republic', language: 'English', isoCode: 'gh' },
  { key: 'guinea', name: 'Guinea', capital: 'Conakry', continent: 'Africa', government: 'Republic', language: 'French', isoCode: 'gn' },
  { key: 'kenya', name: 'Kenya', capital: 'Nairobi', continent: 'Africa', government: 'Republic', language: 'English, Swahili', isoCode: 'ke' },
  { key: 'liberia', name: 'Liberia', capital: 'Monrovia', continent: 'Africa', government: 'Republic', language: 'English', isoCode: 'lr' },
  { key: 'libya', name: 'Libya', capital: 'Tripoli', continent: 'Africa', government: 'Republic', language: 'Arabic', isoCode: 'ly' },
  { key: 'madagascar', name: 'Madagascar', capital: 'Antananarivo', continent: 'Africa', government: 'Republic', language: 'Malagasy, French', isoCode: 'mg' },
  { key: 'mali', name: 'Mali', capital: 'Bamako', continent: 'Africa', government: 'Republic', language: 'French', isoCode: 'ml' },
  { key: 'morocco', name: 'Morocco', capital: 'Rabat', continent: 'Africa', government: 'Constitutional monarchy', language: 'Arabic', isoCode: 'ma' },
  { key: 'saf', name: 'South Africa', capital: 'Pretoria', continent: 'Africa', government: 'Republic', language: 'English, Afrikaans, Zulu, Xhosa', isoCode: 'za' },
  { key: 'somalia', name: 'Somalia', capital: 'Mogadishu', continent: 'Africa', government: 'Republic', language: 'Somali, Arabic', isoCode: 'so' },
  { key: 'sudan', name: 'Sudan', capital: 'Khartoum', continent: 'Africa', government: 'Republic', language: 'Arabic, English', isoCode: 'sd' },
  { key: 'tanzania', name: 'Tanzania', capital: 'Dodoma', continent: 'Africa', government: 'Republic', language: 'English, Swahili', isoCode: 'tz' },
  { key: 'tunisia', name: 'Tunisia', capital: 'Tunis', continent: 'Africa', government: 'Republic', language: 'Arabic', isoCode: 'tn' },
  { key: 'uganda', name: 'Uganda', capital: 'Kampala', continent: 'Africa', government: 'Republic', language: 'English, Swahili', isoCode: 'ug' },
  { key: 'zambia', name: 'Zambia', capital: 'Lusaka', continent: 'Africa', government: 'Republic', language: 'English', isoCode: 'zm' },
  { key: 'zimbabwe', name: 'Zimbabwe', capital: 'Harare', continent: 'Africa', government: 'Republic', language: 'English, Shona, Ndebele', isoCode: 'zw' },
  { key: 'greenland', name: 'Greenland', capital: 'Nuuk', continent: 'North America', government: 'Autonomous territory', language: 'Greenlandic', isoCode: 'gl' },
  { key: 'vatican', name: 'Vatican City', capital: 'Vatican City', continent: 'Europe', government: 'Absolute monarchy', language: 'Italian', isoCode: 'va' },
  { key: 'zealand', name: 'New Zealand', capital: 'Wellington', continent: 'Oceania', government: 'Constitutional monarchy', language: 'English', isoCode: 'nz' },
]; 
